### ISSUE TITLE
Move logic out of controllers

### ISSUE THREAD

**Issue by Quintasan** [Heidr/air-quality#8]
# The main idea

Controllers should remain responsible for handling the incoming parameters and focus on returning the HTML/JSON/whatever you want to return to the browser. Having additional logic inside the controller makes it harder to test and harder to comprehend.

# The case for `HomeController`

Let's take a look at your `HomeController`

```ruby
# app/controllers/home_controller.rb
class HomeController < ApplicationController
  attr_accessor :current_city

  def index

    @stations_map = stations_map('http://api.gios.gov.pl/pjp-api/rest/station/findAll')

    # array with provinces names
    @provinces = provinces(@stations_map)

    # hash with provinces as keys and cities as their values in array
    @province_cities = province_cities(@stations_map, @provinces)

    # hash with cities and their ids
    @cities_with_id = cities_with_id(@stations_map)

    # hash with id and station name in given city
    @city_stations = city_stations(session[:city], @stations_map, @cities_with_id)

    @readings = readings(@city_stations)
  end
end
```

Where do those methods come from? My first guess was that they live in `HomeHelper` but that's not the case. You can find them in `ApplicationController` which is not the exactly right place for it because of a simple reason: all your controllers that inherit from ApplicationController will have them available for no reason.

Taking a short look at https://github.com/Heidr/air-quality/blob/master/app/views/home/index.html.erb makes me sure that none of those instance variables are actually needed there. Another short look at https://github.com/Heidr/air-quality/blob/master/app/views/home/_navbar.html.erb makes me pretty much sure that you need `@provinces` and `@province_cities` instance variables for this view.

So the controller simply could become

```ruby
# app/controllers/home_controller_v2.rb
class HomeControllerV2 < ApplicationController
  def index
    @provinces = function_to_fetch_provinces
    @province_cities = function_to_fetch_provinces_and_the_cities
  end
end
```

# How to handle this?

Use [Service Objects](https://blog.appsignal.com/2020/06/17/using-service-objects-in-ruby-on-rails.html) - essentially a Service Object is and object which encapsulates some kind of task to be realized.

They can be written using "dumb" Ruby class like [this one here](https://github.com/Quintasan/polikompas/blob/master/app/services/process_vote.rb) or you can use some facy-schmancy library like `dry-monads` for this where you get something more complicated like [this wrapper here](https://gitlab.com/Quintasan/fakturownia/-/blob/master/lib/fakturownia/api/invoice.rb)

[There](https://github.com/aaronlasseigne/active_interaction) [are](https://github.com/cypriss/mutations) [some](https://github.com/nebulab/simple_command) [more](https://github.com/actblue/civil_service) [gems](https://github.com/collectiveidea/interactor) for creating service objects but I think you can start simple and just create a PORO (Plain Old Ruby Object) for this one.

# When to use service objects?

I usually write a service object when:

* I have to handle more than one model (so the logic can't go into any of them)
* I have to handle an external service (your case)

# Recommendation

In this particular case, your service object is effectively a wrapper for an HTTP API. My recommendation would be to:

1. Extract the whole logic in `ApplicationController` into a service object, let's call it `GiosApi` (you can put that into `app/services/gios_api.rb`
2. Use the excellent [HTTParty](https://github.com/jnunemaker/httparty) gem instead of fiddling with Net::HTTP which is not the easiest tool in the shed.
3. Refactor the `HomeController` to use the newly created service object
4. Write tests for the service object you just created

**Comment by Heidr** [comment]
I think I'm done with this issue. I wasn't sure how deep I should go with the tests - using specific values (like name of a station) that could change on the external API's side didn't seem like a great idea, so I tested classes of those values.

**Comment by Quintasan** [comment]
@Heidr if you want me to review your code then create a MR for other changes and send me a link
